### ISSUE TITLE
点播打点播放进度bug

### ISSUE THREAD

**Issue by walkingCoder** [LiteAVSDK/Player_Android#107]
【Android】-【7.4.9211】：【点播打点播放进度】
【集成包】：LiteAVSDK_Player_Android_7.4.9211
【当前现象】：Android Studio集成新版本SDK，视频播放完成，点击打点位置，现象是重头播放，应该从打点位置播放，demo 里也有同样的问题。视频播放完成，拖动进度条也是从头播放。 只要是播放完成过一次，就会出现。
【机型】：小米6
【之前版本有无此问题】：问题一直存在
【有无日志或者截图】：

**Comment by sunislee** [comment]
遇到了同样的问题，开源组的人，请尽快给个答复啊

**Comment by dokieyang** [comment]
请升级到最新版本。
