### ISSUE TITLE
窗口模式点击返回内存溢出

### ISSUE THREAD

**Issue by zjw950323** [LiteAVSDK/Player_Android#111]
【Android】-【7.4.9211】：【窗口模式点击返回内存溢出】

【集成包】：LiteAVSDK_Player_Android_7.4.9211
【当前现象】：Android Studio集成新版本SDK，注释掉窗口模式下的点击返回跳转窗口的方法 自己写了一个onBackPressed() 提示内存溢出 onDestroy()中调用了 release()和resetPlayer()
【机型】：华为荣耀9
【之前版本有无此问题】：7.4.9211有,没用过之前的SDK
【有无日志或者截图】：
![8851D40369C2C127AA5947482A5FC07B](https://user-images.githubusercontent.com/31053027/89170538-5d093180-d5b2-11ea-8fd2-93907945a67a.jpg)
![6371AEC81087E9F4E6421052C0AE825F](https://user-images.githubusercontent.com/31053027/89170580-6db9a780-d5b2-11ea-9522-05956428837a.jpg)
![610E7B12793CE4FD553C0985DBC83429](https://user-images.githubusercontent.com/31053027/89170589-70b49800-d5b2-11ea-8bec-67aa46999f4d.jpg)
![C97C77093A8D85D7C7802EAE12E98A86](https://user-images.githubusercontent.com/31053027/89170594-74481f00-d5b2-11ea-9c15-b53f4d522469.jpg)

**Comment by dokieyang** [comment]
请升级到最新版本。
