### ISSUE TITLE
在ScrollView中添加多个SuperPlayerView，无法全屏 android

### ISSUE THREAD

**Issue by Lucidastar** [LiteAVSDK/Player_Android#123]
在ScrollView中添加多个SuperPlayerView，进行全屏时，会把其他的控件顶上去，无法进行整个界面的覆盖，达不到全屏的效果，有好的解决方案吗

**Comment by 284419487** [comment]
所谓的全屏指的是播放画面view最大化，通过把状态栏隐藏或透明；

所以超级播放器在实现全屏的时候也是有对状态栏做处理；

当自己的项目也是有做沉浸式开发状态栏时看能会跟超级播放器的逻辑有冲突；

解决办法： 1.部分有黑（白）边的手机用我们的dmeo是否也会有同样问题？

    2.检查一下自己项目的沉浸式状态栏逻辑，注释掉试一下，或者把我们的代码逻辑注释掉调试一下

**Comment by OhZheng** [comment]
您好，请问这个问题将您解决了吗？
