### ISSUE TITLE
播放地址过长？ffp_prepare_async_l too long url

### ISSUE THREAD

**Issue by mxruan** [LiteAVSDK/Player_Android#124]
播放m3u8视频报以下异常，是不是m3u8或ts的url过长导致的：

E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-10002-1] cancelBuffer: BufferQueue has been abandoned
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [10919] didn't call SDL_JNI_DetachThreadEnv() explicity
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [10921] didn't call SDL_JNI_DetachThreadEnv() explicity
E/IJKMEDIA: ffp_prepare_async_l too long url
E/IJKMEDIA: ijklongurl:: Server returned 400 Bad Request
E/com.tencent.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/TXCVodVideoView: onError: -10000,0
 E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [10932] didn't call SDL_JNI_DetachThreadEnv() explicity

**Comment by dokieyang** [comment]
新版本已修复
