### ISSUE TITLE
播放m3u8报错：IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!

### ISSUE THREAD

**Issue by zhouwenhao** [LiteAVSDK/Player_Android#126]
![image](https://user-images.githubusercontent.com/5159963/100826134-a4d29380-3494-11eb-9737-bd0bd7bae8a2.png)

E/IJKMEDIA: skip open segment of playlist 0, seq 661
E/IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!
W/IJKMEDIA: Failed to open segment of playlist 0, seq
E/IJKMEDIA: skip open segment of playlist 0, seq 662
E/IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!
W/IJKMEDIA: Failed to open segment of playlist 0, seq
E/IJKMEDIA: skip open segment of playlist 0, seq 663
E/IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!
W/IJKMEDIA: Failed to open segment of playlist 0, seq
E/IJKMEDIA: skip open segment of playlist 0, seq 664
E/IJKMEDIA: Protocol 'https' not on whitelist 'file,crypto'!
W/IJKMEDIA: Failed to open segment of playlist 0, seq
E/IJKMEDIA: skip open segment of playlist 0, seq 665
E/IJKMEDIA: Error when loading first segment 'https://*******/video/netdisk-videotran-yangquan/8b
E/IJKMEDIA: /data/user/0/com.juexiao.emm/files/test.m3u8: Invalid data found when processing input
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7049]
E/TXCVodVideoView: onHLSKeyError
I/TXCVodVideoView: sendSimpleEvent -2305 hls key error
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7047]
I/TextureRenderView: releaseSurfaceTexture: alive: re-attach SurfaceTexture to TextureView
E/com.tencent.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
D/IJKMEDIA: ffpipeline_set_surface()

**Comment by dokieyang** [comment]
请升级到最新版本。
