### ISSUE TITLE
恳请提供x86版本的so文件，哪怕无法播放也方便在模拟器上测试。

### ISSUE THREAD

**Issue by LiuDeng** [LiteAVSDK/Player_Android#133]
如题，感谢~

**Comment by Tencent-Alice** [comment]
您好，暂不支持的 ，非常抱歉了，如下图 
![image](https://user-images.githubusercontent.com/74762384/103849267-272b2480-50df-11eb-80c2-c7d199746702.png)
技术问题，欢迎交流，Q2562367495 注明来意
