### ISSUE TITLE
demo的列表播放跟这个不一样吧？

### ISSUE THREAD

**Issue by xuzh2017** [LiteAVSDK/Player_Android#142]

**Comment by xuzh2017** [comment]
https://github.com/tencentyun/SuperPlayer_Android/issues/91#issue-616421001
这个是列表中播放，全屏播放好像现在的横竖屏切换方式不行

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，目前使用的版本号是多少，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意
