### ISSUE TITLE
高斯拓边

### ISSUE THREAD

**Issue by chapliny** [LiteAVSDK/Player_Android#144]
想请教下高斯模糊 拓边 这种怎么实现。或者实现的思路。
【Android】-【7.4.9211】：【播放HLS黑屏】
【集成包】：LiteAVSDK_Player_Android_7.4.9211
【当前现象】： 无
【机型】：无
【之前版本有无此问题】：无
【有无日志或者截图】：暂无日志

**Comment by chapliny** [comment]
![image](https://user-images.githubusercontent.com/3133328/114154702-442bf980-9953-11eb-82f2-050be87a8e1b.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，需要您这边业务侧来进行完成的，可以在播放器上面添加一层模糊的蒙版来进行实现，请知悉
技术问题 欢迎交流 q2562367495注明来意
