### ISSUE TITLE
rtsp协议是否支持？是否有延迟？

### ISSUE THREAD

**Issue by 369406145** [LiteAVSDK/Player_Android#145]
是否支持rtsp 流播放  rtsp:用户名/密码@192.168.2.1:554
返回的数据是否有每一帧的回调数据，然后上传到服务器进行音视频通话

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，请问播放器sdk的版本号是多少，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
您好，目前播放器sdk 暂不支持rtsp协议，支持的协议有hls mp4 flv 
如还有问题 欢迎交流 q2562367495 注明来意
