### ISSUE TITLE
手机系统设置15秒屏幕熄屏，集成进来播放视频的时候，视频播放到15秒后，播放界面跟着系统一起熄屏，这是什么情况？

### ISSUE THREAD

**Issue by Achenglove** [LiteAVSDK/Player_Android#146]

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以提供下播放器sdk版本号，和复现视频，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Achenglove** [comment]
com.tencent.liteav:LiteAVSDK_Professional:7.7.9457   熄屏这个如何处理不跟随系统设置的呢？

**Comment by Tencent-Alice** [comment]
您好，上述问题复现是通过什么操作实现的？可以简单描述下
技术问题 欢迎交流 q2562367495 注明来意

**Comment by Beardemon** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/14085190/169704594-a972da52-ca17-498c-88b4-35ed341bebb3.png">
添加这个属性就行了
