### ISSUE TITLE
关于播放器静音功能

### ISSUE THREAD

**Issue by kHRYSTAL** [LiteAVSDK/Player_Android#148]
issue标题：关于播放器静音功能

【Android】-【lastest】：【没有暴露setVolume的api】
issue内容：默认静音或播放时通过api控制音量做不到
【当前现象】：播放不能通过配置或代码控制播放器音量
【集成包】：lastest

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，没有相应的api接口，请知悉
1 web端设置音量您可参考该文档
https://cloud.tencent.com/document/product/881/30824``
https://cloud.tencent.com/document/product/881/20207
2其他端 可以使用setMute方法
技术问题 欢迎交流 q2562367495 注明来意
