### ISSUE TITLE
希望能够增加获取播放的帧数 帧率 缓存时间 卡顿次数的功能

### ISSUE THREAD

**Issue by mengsiyitiaojie** [LiteAVSDK/Player_Android#152]
希望能够增加获取播放的帧数 帧率 缓存时间 卡顿次数的功能

**Comment by Tencent-Alice** [comment]
您好，目前这些功能暂不支持，建议已经收到，会反馈到产品后端评估优化，敬请期待……
技术问题 欢迎交流 q2562367945 注明来意

**Comment by mengsiyitiaojie** [comment]
> 您好，目前这些功能暂不支持，建议已经收到，会反馈到产品后端评估优化，敬请期待……
> 技术问题 欢迎交流 q2562367945 注明来意

现在可以这些功能支持了吗

**Comment by mengsiyitiaojie** [comment]
> 您好，目前这些功能暂不支持，建议已经收到，会反馈到产品后端评估优化，敬请期待……
> 技术问题 欢迎交流 q2562367945 注明来意

现在这些功能可以支持了吗

**Comment by dokieyang** [comment]
点播播放数据 ： https://cloud.tencent.com/document/product/881/80518
