### ISSUE TITLE
变速播放小于1倍的时候声音有问题(iOS SDK正常)

### ISSUE THREAD

**Issue by lxp-git** [LiteAVSDK/Player_Android#156]
- 【Android】-【8.8.10254】：【变速播放的慢速播放】
- 【集成包】：LiteAVSDK_Player_Android_8.8.10254
- 【当前现象】：变速播放采用小于1倍(0.5倍，0.8倍)的慢速播放时，声音有问题。卡卡的。iOS没有这个问题。貌似跟机型无关，都有问题。
- 【机型】：Mi 8 Lite
- 【之前版本有无此问题】：有
- 【有无日志或者截图】：暂无日志

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以录制视频看下，这是偶发还是必现问题，便于进一步排查
技术问题 欢迎交流 q2562367495 注明来意
