### ISSUE TITLE
超级播放器播放到一定时间进入缓冲后就卡着不动播放不了

### ISSUE THREAD

**Issue by SoloLee** [LiteAVSDK/Player_Android#158]
【Android】-【6.7.7754】：【播放视频卡着不能播放】
【集成包】：LiteAVSDK_Player_Android_6.7.7754
【当前现象】：播放器一个mp4地址视频，到一定时间进入缓冲，卡着就再也播放不了。最后回调到-2301，网络断开，播放错误。视频链接在浏览器中可以正常播放，视频下载本地也可以正常播放。
【机型】：如OPPO K1，Honor10
【之前版本有无此问题】：当前最新版本运行DEMO也存在此问题
![image](https://user-images.githubusercontent.com/4515216/123535941-01abd900-d75a-11eb-8c01-7654bbe3a6d8.png)
![image](https://user-images.githubusercontent.com/4515216/123535990-4afc2880-d75a-11eb-9f64-a31bc8b8e3a7.png)
![image](https://user-images.githubusercontent.com/4515216/123535995-52233680-d75a-11eb-9e8e-75679ac8d624.png)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，这边用华为mate20进行测试mp4固定视频，进度条正常，如下图
![A858FAD3-9BB8-4651-8964-5474C912EE5A](https://user-images.githubusercontent.com/74762384/124211904-831bb680-db20-11eb-9e17-4f0493007f9e.jpeg)

https://cloud.tencent.com/document/product/881/20204测试的demo可以尝试下
另外是只有上述两个机型存在这个问题吗

如有技术问题， 欢迎继续交流 q2562367495 注明来意

**Comment by SoloLee** [comment]
目前删除本地缓存视频个数的代码，视频可以正常播放了。
原因未知。具体原因能否解答一下？
![image](https://user-images.githubusercontent.com/4515216/124751892-ba8fc600-df59-11eb-8908-013fdf20ed16.png)

**Comment by Tencent-Alice** [comment]
您好 &nbsp;可以加我Q哈 方便交互



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 晚上7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tencentyun/SuperPlayer_Android] 超级播放器播放到一定时间进入缓冲后就卡着不动播放不了 (#158)





 
目前删除本地缓存视频个数的代码，视频可以正常播放了。
 原因未知。具体原因能否解答一下？

**Comment by SoloLee** [comment]
已经定位到问题，解决了。
就是不知道原因，有技术解答一下吗？
