### ISSUE TITLE
请问这个支持竖屏的全屏播放吗，如果支持怎么设置

### ISSUE THREAD

**Issue by yujunhua93** [LiteAVSDK/Player_Android#159]
请问这个支持竖屏的全屏播放吗，如果支持怎么设置

**Comment by Tencent-Alice** [comment]
您好，您现在遇到了什么情况呢，竖屏时全屏效果，可以用铺满的方式，不会留下黑边情况
如有问题 欢迎交流 q2562367495 注明来意
