### ISSUE TITLE
多次调用startDownloadUrl下载【同一个URL】会导致监听回调多次的情况，有办法解决么，或者说能否提供判断url是否正在下载的判断方法？

### ISSUE THREAD

**Issue by asCoder-Bill** [LiteAVSDK/Player_Android#163]

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，确认下您这边是什么终端，收到多次回调是哪一个回调信息呢，和您确认下
技术问题 欢迎交流 q2562367495 注明来意

**Comment by asCoder-Bill** [comment]
你好，我这边是安卓的小米11，ios那边也是遇到相同情况，而且多次调用startDownloadUrl下载【同一个URL】后，这个下载任务无法停止，调用stopDownload后在onDownloadStop会有回调，但是onDownloadProgress还在继续。
多次调用startDownloadUrl下载【同一个URL】感觉像是开启了多个下载任务，每次都会有onDownloadStart，相应的onDownloadProgress也会有多次。

**Comment by Tencent-Alice** [comment]
您好，收到任务停止就可以，进度回调还在继续 回调的进度值还有变化吗
![AA1592D4-BDCA-4F03-AC54-EF528D1E4768](https://user-images.githubusercontent.com/74762384/129136697-bb4ded9f-f751-4703-ad1c-1a75503c711c.jpeg)
技术问题 欢迎交流 q2562367495 注明来意

**Comment by asCoder-Bill** [comment]
我是通过TXVodDownloadMediaInfo携带的url判断的，我的意思是单次调用startDownloadUrl下载没有问题，比如下载进度：[0]  [0.1]  [0.31]  [0.66]  [0.78]  [0.89]  [1.0]。
但是，在【同一个url】还没下载完的时候再次调用 startDownloadUrl(“同一个url”)，就会出现（通过TXVodDownloadMediaInfo携带的url判断）下载进度： [0]  [0.05]  [0.11 (0.1)]  [0.26 (0.22)]  [0.32 (0.301)]  [0.44 (0.43)]  [0.576 (0.555)] ..... 并导致进度条左右横跳。
期间调用一次stopDownload(txVodDownloadMediaInfo)后，下载进度回调并没有完全停止。似乎sdk内部并没有对url是否正在下载进行判断。 请注意我并使用多个不同url下载，是使用同一个url进行多次下载。
