### ISSUE TITLE
【Android】-【9.0.10437】：【TXLiteAVSDK_Player集成后，包体新增了5M，太大了】

### ISSUE THREAD

**Issue by weidongjian** [LiteAVSDK/Player_Android#165]
【Android】-【9.0.10437】：【TXLiteAVSDK_Player集成后，包体新增了5M】
【集成包】：LiteAVSDK_Player_Android_9.0.10437
【当前现象】：集成上面版本的SDK后，在开启混淆后，apk的包体还新增了5M，增加太多了，无法接受
【机型】：如华为Mate 20
【之前版本有无此问题】：未知
【其他】：这边只想集成点播功能，不需要直播功能

**Comment by weidongjian** [comment]
fix

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，需求是想通过短视频sdk来集成云点播产品吗？方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意

**Comment by DoveBarnett** [comment]
> 【Android】-【9.0.10437】：【TXLiteAVSDK_Player集成后，包体新增了5M】 【集成包】：LiteAVSDK_Player_Android_9.0.10437 【当前现象】：集成上面版本的SDK后，在开启混淆后，apk的包体还新增了5M，增加太多了，无法接受 【机型】：如华为Mate 20 【之前版本有无此问题】：未知 【其他】：这边只想集成点播功能，不需要直播功能

请问这个9.0.10437版本号是看哪里知道的？
