### ISSUE TITLE
视频列表中，滑上去之后，带播放器的item会往下滑一点，不会停到滑动位置

### ISSUE THREAD

**Issue by wuh876** [LiteAVSDK/Player_Android#170]
name: 'LiteAVSDK_Professional_8.5.10026', ext: 'aar'

视频列表中，滑上去之后，带播放器的item会往下滑一点，不会停到滑动位置，然后，视频下方的view滑不上来

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以视频复现下吗，方便进一步定位问题
技术问题 欢迎交流 q2562367495 注明来意
