### ISSUE TITLE
请问解码器支持哪些音频格式？

### ISSUE THREAD

**Issue by huozhihao** [LiteAVSDK/Player_Android#171]
请问解码器支持哪些音频格式？
amr,m4a,wav支持吗

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，这些音频格式都是支持的，技术问题 欢迎交流 q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
播放器sdk是来源的，对解码器不做限制，可以自行下载，和播放器sdk没啥关系的
