### ISSUE TITLE
MIUI12.5.6 ，播放器音量滑动BUG

### ISSUE THREAD

**Issue by DNJusername** [LiteAVSDK/Player_Android#175]
【Android】-【7.4.9211】：【播放视频，音量调节直接静音或无效果】
【集成包】："com.tencent.liteav:LiteAVSDK_Professional:latest.release"
【当前现象】：Android Studio集成新版本SDK，音量滑动直接静音或者无效果。手机跑你们的Git Demo同样有这个问题
【机型】：小米10
【之前版本有无此问题】：一直有这个问题
【有无日志或者截图】：

**Comment by LxzBUG** [comment]
一直不解决。。。

**Comment by chapery** [comment]
小米cc9，MIUI12.5.4 有同样的问题

**Comment by chapery** [comment]
`VideoGestureDetector.check` 方法中的 `VOLUME` 条件分支第一次执行时 height 为 0 造成的。

**Comment by Beardemon** [comment]
改成这样就行了

case VOLUME:
                float value = height / Float.valueOf(mMaxVolume) ;
                int newVolume = value > 0 ? (int) ((downEvent.getY() - moveEvent.getY()) / value * mSensitivity + mOldVolume) : mOldVolume;
                mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC, newVolume, AudioManager.FLAG_PLAY_SOUND);

                float volumeProgress = newVolume / Float.valueOf(mMaxVolume) * 100;
                if (mVideoGestureListener != null) {
                    mVideoGestureListener.onVolumeGesture(volumeProgress);
                }

                break;

**Comment by dokieyang** [comment]
新版已经fix
