### ISSUE TITLE
直接跑demo，Android12 安装失败，提示安装包异常

### ISSUE THREAD

**Issue by mangotangtang** [LiteAVSDK/Player_Android#184]
* 【Android】-【9.3.10764】：【Android12 安装失败，提示安装包异常】
* 【集成包】：LiteAVSDK_Player_Android_9.3.10764
* 【当前现象】：Android Studio集成新版本SDK，直接跑demo安装失败，  项目中也引用了SDK，播放闪退
* 【机型】：一加9Pro
* 【之前版本有无此问题】：
* 【有无日志或者截图】：暂无日志

**Comment by mangotangtang** [comment]
请问Android12 有适配嘛

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 是参考的这个demo吗(https://cloud.tencent.com/document/product/881/20204)  ，可以提供下报错截图，方便进一步定位case 
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
暂时没有适配android 12，请知悉

**Comment by mangotangtang** [comment]
参考的是https://github.com/tencentyun/SuperPlayer_Android 这个demo
