### ISSUE TITLE
个别机型直播使用V2TXLivePlayer播放直播，发现断网或者暂停直播，点击全屏按钮，画面显示错乱未铺满

### ISSUE THREAD

**Issue by zengkunqiang** [LiteAVSDK/Player_Android#198]
点播：使用点播的情况无此问题。
直播：直播的仅在出现暂停或者断网（即没有流去渲染情况下出现），正常播放直播不会出现此问题。

问题机型
手机型号: 小米11
手机版本：MIUI13.0.5稳定版
系统: Android12

正常机型
型号:华为JDN2-W09
版本:2.0.0141
系统: HarmonyOs（2.0.0）

https://user-images.githubusercontent.com/17756132/155463984-eecf82c6-7355-412b-9b45-e37ddea13bd8.mp4

**Comment by zengkunqiang** [comment]
使用的sdk版本com.tencent.liteav:LiteAVSDK_Professional:9.5.11201

**Comment by 284419487** [comment]
切换全屏用的是哪个控件？检查下控件的宽高是否正常

**Comment by dokieyang** [comment]
建议升级到最新版本进行使用，9.5 版本已经是很旧的一个版本了
