### ISSUE TITLE
我改了一下进度跳转, 可以通过点击进度条直接跳转进度, 但是出现了seekbar会往回波动一下的情况

### ISSUE THREAD

**Issue by HancockY** [LiteAVSDK/Player_Android#21]
我改了一下进度跳转, 可以通过点击进度条直接跳转到点击位置, 但是出现了seekbar会往回波动一下的情况. 之前看GSY那个开源项目说的是关键帧的问题, 然后有代码可以设置解决, 这个项目里面改怎么处理啊

**Comment by HancockY** [comment]
是因为ijk的FFMPEG对关键帧处理逻辑问题么?

**Comment by AlphaHans** [comment]
是的，如果gop过大会导致上述情况

**Comment by HancockY** [comment]
请问这个有解决的方案么?

**Comment by AlphaHans** [comment]
你好，这个暂时未有，放到plan里面，后面看下怎么支持一下。

**Comment by jacky-zhupengpeng** [comment]
哪位大哥能指点一下  为什么开启全屏模式 之前的activity全部销毁了
