### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by gxp3635** [LiteAVSDK/Player_Android#212]
Android版。使用的最新sdk,  播放卡顿的时候报错
E/PlayerCore: [TPFFmpegLib][TPFFmpegLog.cpp:73](level:24)adjacent packets position have large gap, (packet 236512->236942, cache 694294->727062, seek 1031 times), if this message appears too often, try option max_dts_jitter

**Comment by gxp3635** [comment]
max_dts_jitter  这个需要怎么配置

**Comment by dokieyang** [comment]
出现此问题，建议对视频源本身进行优化

**Comment by Liveqing** [comment]
同样的第三方视频地址播放, ios就很流畅, Android的也是报这个错, 卡的根本看不了
