### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by BDragonKS** [LiteAVSDK/Player_Android#214]
issue标题：

【Android】-【9.0】：【无法播放】
issue内容：

【当前现象】：无法播放
【集成包】：LiteAVSDK_Player_Android_7.2.8927
【机型】：vivo Y3 V1901A
【之前版本有无此问题】：同一版本，之前能播放，后续出现无法播放
【有无日志或者描述、截图】：[TXCIOListener.cpp, operator, 668]:del event failed|EPOLL_CTL_DEL: fd 338|error:2

**Comment by BDragonKS** [comment]
![image](https://user-images.githubusercontent.com/16713425/176069885-e81f8ebb-82a8-4f8c-8164-0d9084d95c1d.png)

**Comment by dokieyang** [comment]
> issue标题：
> 
> 【Android】-【9.0】：【无法播放】 issue内容：
> 
> 【当前现象】：无法播放 【集成包】：LiteAVSDK_Player_Android_7.2.8927 【机型】：vivo Y3 V1901A 【之前版本有无此问题】：同一版本，之前能播放，后续出现无法播放 【有无日志或者描述、截图】：[TXCIOListener.cpp, operator, 668]:del event failed|EPOLL_CTL_DEL: fd 338|error:2

请升级到最新版本SDK： 10.2.0.11131
