### ISSUE TITLE
【android】-【10.4.0.11165】：【播放器内存泄漏】

### ISSUE THREAD

**Issue by MrLizhiguang** [LiteAVSDK/Player_Android#216]
┬───
 │ GC Root: Global variable in native code
 │
 ├─ dalvik.system.PathClassLoader instance
 │    Leaking: NO (TPDLProxyLog↓ is not leaking and A ClassLoader is never leaking)
 │    ↓ ClassLoader.runtimeInternalObjects
 ├─ java.lang.Object[] array
 │    Leaking: NO (TPDLProxyLog↓ is not leaking)
 │    ↓ Object[2994]
 ├─ com.tencent.thumbplayer.core.downloadproxy.utils.TPDLProxyLog class
 │    Leaking: NO (a class is never leaking)
 │    ↓ static TPDLProxyLog.mLogListener
 │                          ~~~~~~~~~~~~
 ├─ com.tencent.liteav.thumbplayer.ThumbMediaPlayer$4 instance
 │    Leaking: UNKNOWN
 │    Retaining 560.3 kB in 6990 objects
 │    Anonymous class implementing com.tencent.thumbplayer.core.downloadproxy.api.ITPDLProxyLogListener
 │    ↓ ThumbMediaPlayer$4.this$0
 │                         ~~~~~~
 ├─ com.tencent.liteav.thumbplayer.ThumbMediaPlayer instance
 │    Leaking: UNKNOWN
 │    Retaining 560.3 kB in 6989 objects
 │    ↓ ThumbMediaPlayer.mSurfaceTextureHost
 │                       ~~~~~~~~~~~~~~~~~~~
 ├─ com.tencent.liteav.txcvodplayer.renderer.TextureRenderView$b instance
 │    Leaking: UNKNOWN
 │    Retaining 546.4 kB in 6833 objects
 │    ↓ TextureRenderView$b.i
 │                          ~
 ├─ java.util.concurrent.ConcurrentHashMap instance
 │    Leaking: UNKNOWN
 │    Retaining 546.3 kB in 6830 objects
 │    ↓ ConcurrentHashMap[key()]
 │                       ~~~~~~~
 ├─ com.tencent.liteav.txcvodplayer.TXCVodVideoView$5 instance
 │    Leaking: UNKNOWN
 │    Retaining 546.1 kB in 6826 objects
 │    Anonymous class implementing com.tencent.liteav.txcvodplayer.renderer.a$a
 │    ↓ TXCVodVideoView$5.a
 │                        ~
 ├─ com.tencent.liteav.txcvodplayer.TXCVodVideoView instance
 │    Leaking: UNKNOWN
 │    Retaining 546.1 kB in 6825 objects
 │    View not part of a window view hierarchy
 │    View.mAttachInfo is null (view detached)
 │    View.mWindowAttachCount = 0
 │    u instance of cn.guangheO2Oswl.MyApplication
 │    mContext instance of cn.guangheO2Oswl.MyApplication
 │    ↓ TXCVodVideoView.x │                      ~
 ├─ com.tencent.liteav.txcvodplayer.renderer.TextureRenderView instance
 │    Leaking: YES (View.mContext references a destroyed activity)
 │    Retaining 822 B in 13 objects
 │    View not part of a window view hierarchy
 │    View.mAttachInfo is null (view detached)
 │    View.mWindowAttachCount = 1
 │    mContext instance of com.guanghe.shortvideo.activity.discover.DiscoverVideoActivity with mDestroyed = true
 │    ↓ View.mContext
 ╰→ com.guanghe.shortvideo.activity.discover.DiscoverVideoActivity instance
 ​     Leaking: YES (ObjectWatcher was watching this because com.guanghe.shortvideo.activity.discover.
​     DiscoverVideoActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     Retaining 80.4 kB in 1369 objects
 ​     key = d8a9cf63-214e-42ef-b83b-8d6c08b421b5
 ​     watchDurationMillis = 7030
 ​     retainedDurationMillis = 2028
 ​     mApplication instance of cn.xx.MyApplication
 ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper

**Comment by Tencent-Alice** [comment]
您好，可以具体描述下您的问题吗，方便进一步定位
技术问题，欢迎交流，q2562367495

**Comment by dokieyang** [comment]
最新版本已经修复，请升级到10.7 版本的SDK
