### ISSUE TITLE
视频黑屏，没画面

### ISSUE THREAD

**Issue by wuh876** [LiteAVSDK/Player_Android#220]
可以播放，视频黑屏，没画面

**Comment by Tencent-Alice** [comment]
您好 根据您的问题，  只是黑屏吗，是否有声音呢， 可以提供下复现视频吗？
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by wuh876** [comment]
有声音没画面，用简约版可以播放，专业版就不行

**Comment by dokieyang** [comment]
麻烦提供下播放视频的链接， 如果可以最好提供下详细的log
