### ISSUE TITLE
如何播放raw和assets音频文件

### ISSUE THREAD

**Issue by LvBing1995** [LiteAVSDK/Player_Android#223]

**Comment by Tencent-Alice** [comment]
HI 根据您的问题 安卓客户端sdk，播放器支持播放两种文件：1、在线url；2、手机本地的视频文件

**Comment by Tencent-Alice** [comment]
HI 根据您的问题 安卓客户端sdk，播放器支持播放两种文件：1、在线url；2、手机本地的视频文件 。如果是apk里面的raw、assets资源文件，建议您使用安卓系统播放器 技术问题 欢迎交流 Q2562367495 注明来意

**Comment by dokieyang** [comment]
可以先复制到sdcard，然后传入绝对路径进行播放
