### ISSUE TITLE
11.4.0.13189这个版本TXCVodVideoView，在android13 一加手机内存泄漏

### ISSUE THREAD

**Issue by Wangyan0415-git** [LiteAVSDK/Player_Android#225]
D  ​
D  ┬───
D  │ GC Root: Thread object
D  │
D  ├─ android.os.HandlerThread instance
D  │    Leaking: NO (MessageQueue↓ is not leaking)
D  │    Thread name: 'TP-workthread'
D  │    ↓ HandlerThread.mLooper
D  ├─ android.os.Looper instance
D  │    Leaking: NO (MessageQueue↓ is not leaking)
D  │    ↓ Looper.mQueue
D  ├─ android.os.MessageQueue instance
D  │    Leaking: NO (MessageQueue#mQuitting is false)
D  │    HandlerThread: "TP-workthread"
D  │    ↓ MessageQueue[0]
D  │                  ~~~
D  ├─ android.os.Message instance
D  │    Leaking: UNKNOWN
D  │    Retaining 68 B in 2 objects
D  │    Message.what = 30
D  │    Message.when = 594445845 (5630 ms before heap dump)
D  │    Message.obj = object array @320468424 of java.lang.Object[]
D  │    Message.callback = null
D  │    Message.target = instance @315682560 of com.tencent.thumbplayer.utils.q$a
D  │    ↓ Message.target
D  │              ~~~~~~
D  ├─ com.tencent.thumbplayer.utils.q$a instance
D  │    Leaking: UNKNOWN
D  │    Retaining 32 B in 1 objects
D  │    ↓ q$a.a
D  │          ~
D  ├─ com.tencent.thumbplayer.utils.q instance
D  │    Leaking: UNKNOWN
D  │    Retaining 152 B in 7 objects
D  │    ↓ q.e
D  │        ~
D  ├─ com.tencent.thumbplayer.tplayer.b instance
D  │    Leaking: UNKNOWN
D  │    Retaining 618.2 kB in 8930 objects
D  │    ↓ b.c
D  │        ~
D  ├─ com.tencent.thumbplayer.tplayer.c instance
D  │    Leaking: UNKNOWN
D  │    Retaining 617.9 kB in 8914 objects
D  │    ↓ c.a
D  │        ~
D  ├─ com.tencent.liteav.thumbplayer.ThumbMediaPlayerListener instance
D  │    Leaking: UNKNOWN
D  │    Retaining 617.8 kB in 8912 objects
D  │    ↓ ThumbMediaPlayerListener.mThumbMediaPlayer
D  │                               ~~~~~~~~~~~~~~~~~
D  ├─ com.tencent.liteav.thumbplayer.ThumbMediaPlayer instance
D  │    Leaking: UNKNOWN
D  │    Retaining 617.8 kB in 8911 objects
D  │    ↓ ThumbMediaPlayer.mSurfaceTextureHost
D  │                       ~~~~~~~~~~~~~~~~~~~
D  ├─ com.tencent.liteav.txcvodplayer.renderer.TextureRenderView$b instance
D  │    Leaking: UNKNOWN
D  │    Retaining 617.2 kB in 8902 objects
D  │    ↓ TextureRenderView$b.i
D  │                          ~
D  ├─ java.util.concurrent.ConcurrentHashMap instance
D  │    Leaking: UNKNOWN
D  │    Retaining 617.1 kB in 8899 objects
D  │    ↓ ConcurrentHashMap[key()]
D  │                       ~~~~~~~
D  ├─ com.tencent.liteav.txcvodplayer.TXCVodVideoView$6 instance
D  │    Leaking: UNKNOWN
D  │    Retaining 616.9 kB in 8895 objects
D  │    Anonymous class implementing com.tencent.liteav.txcvodplayer.renderer.a$a
D  │    ↓ TXCVodVideoView$6.a
D  │                        ~
D  ├─ com.tencent.liteav.txcvodplayer.TXCVodVideoView instance
D  │    Leaking: YES (View.mContext references a destroyed activity)
D  │    Retaining 616.9 kB in 8894 objects
D  │    View not part of a window view hierarchy
D  │    View.mAttachInfo is null (view detached)
D  │    View.mWindowAttachCount = 0
D  │    w instance of com.zhisland.android.blog.common.app.ZhislandApplication
D  │    mContext instance of com.zhisland.android.blog.live.view.impl.ActLiveRoom with mDestroyed = true
D  │    ↓ View.mContext
D  ╰→ com.zhisland.android.blog.live.view.impl.ActLiveRoom instance
D  ​     Leaking: YES (ObjectWatcher was watching this because com.zhisland.android.blog.live.view.impl.ActLiveRoom
D  ​     received Activity#onDestroy() callback and Activity#mDestroyed is true)
D  ​     Retaining 36.4 kB in 647 objects
D  ​     key = bbecd9ed-e03e-41f5-ba57-55a21cf00e68
D  ​     watchDurationMillis = 5640
D  ​     retainedDurationMillis = 640
D  ​     mApplication instance of com.zhisland.android.blog.common.app.ZhislandApplication
D  ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
D  
D  METADATA
D  
D  Build.VERSION.SDK_INT: 33
D  Build.MANUFACTURER: OnePlus
D  LeakCanary version: 2.12
D  App process name: com.zhisland.android.blog
D  Class count: 33376
D  Instance count: 414125
D  Primitive array count: 207648
D  Object array count: 53489
D  Thread count: 228
D  Heap total bytes: 47338023
D  Bitmap count: 515
D  Bitmap total bytes: 71102251
D  Large bitmap count: 0
D  Large bitmap total bytes: 0
D  Db 1: open /data/user/0/com.zhisland.android.blog/files/1400507957_37313034333538313635383630333139323336/msg_0.db
D  Db 2: open /data/user/0/com.zhisland.android.blog/files/1400507957_37313034333538313635383630333139323336/im.db
D  Db 3: open /data/user/0/com.zhisland.android.blog/databases/pushwgs.db
D  Db 4: open /data/user/0/com.zhisland.android.blog/databases/pushg3.db
D  Db 5: closed /data/user/0/com.zhisland.android.blog/databases/monitor.db
D  Db 6: closed /data/user/0/com.zhisland.android.blog/databases/logger.db
D  Db 7: open /data/user/0/com.zhisland.android.blog/databases/zhisland.db
D  Db 8: closed /data/user/0/com.zhisland.android.blog/databases/ua.db
D  Db 9: open /data/user/0/com.zhisland.android.blog/databases/bugly_db_
D  Db 10: open /data/user/0/com.zhisland.android.blog/databases/dim.db
D  Db 11: open /data/user/0/com.zhisland.android.blog/databases/gtc3.db
D  Db 12: open /data/user/0/com.zhisland.android.blog/databases/cg.db
D  Db 13: closed /data/user/0/com.zhisland.android.blog/databases/umeng_zero_cache.db
D  Db 14: open /data/user/0/com.zhisland.android.blog/databases/zx.db
D  Db 15: closed /data/user/0/com.zhisland.android.blog/databases/ua.db
D  Db 16: open /data/user/0/com.zhisland.android.blog/databases/ua.db
D  Stats: LruCache[maxSize=3000,hits=190976,misses=385719,hitRate=33%]
D  RandomAccess[bytes=22453858,reads=385719,travel=216686940791,range=56183346,size=67226481]
D  Analysis duration: 14508 ms

**Comment by dokieyang** [comment]
请问每次播放完成或退出页面有调用播放器的stopPlay （com.tencent.rtmp.TXVodPlayer#stopPlay）接口吗

**Comment by Wangyan0415-git** [comment]
> 请问每次播放完成或退出页面有调用播放器的stopPlay （com.tencent.rtmp.TXVodPlayer#stopPlay）接口吗
每次退出都会调用
public void release() {
        if (mLivePlayer != null) {
            log.INSTANCE.i("release live player");
            mLivePlayer.stopPlay(true);
            mLivePlayer = null;
        }
        if (mVodPlayer != null) {
            log.INSTANCE.i("release vod player");
            mVodPlayer.stopPlay(true);
            mVodPlayer = null;
        }
        if (mVideoView != null) {
            log.INSTANCE.i("release video view");
            mVideoView.removeVideoView();
            mVideoView.onDestroy();
            mVideoView = null;
        }
    }

**Comment by dokieyang** [comment]
@Wangyan0415-git 请问你方便提供最小化可以复现上面内存泄漏的demo 工程吗，谢谢。
