### ISSUE TITLE
【安卓】-【9.5.29040】：【m3u8中有分片404会播放失败】

### ISSUE THREAD

**Issue by shmy** [LiteAVSDK/Player_Android#226]
【集成包】：LiteAVSDK_Player_Android_9.5.29040
【当前现象】：Android Studio集成新版本SDK，播放器一个HLS地址的视频，如果其中一个ts分片服务器返回404或者401，播放器会重试几次然后失败；
【机型】：一加5T
【期望】：是否有能力可以跳过错误的分片继续播放，谢谢

**Comment by dokieyang** [comment]
9.5版本已经不维护了, 请问您更新到最新的11.4 版本验证下
如果问题还存储, 欢迎提供播放视频的url

**Comment by shmy** [comment]
最新版本，也会卡住很久，
卡住段 1:09
[1.m3u8.zip](https://github.com/LiteAVSDK/Player_Android/files/13635622/1.m3u8.zip)

**Comment by Tencent-Alice** [comment]
您好 播放器技术问题 欢迎交流 Q2562367495 注明来意
