### ISSUE TITLE
定制点播播放器，播放hls地址时的默认码率/硬件加速选项问题

### ISSUE THREAD

**Issue by ZhZhZhen** [LiteAVSDK/Player_Android#85]
我看超级播放器是在，视频准备后设置一次默认码率，我这样写，有时候会偶现开始时屏幕闪一下的问题，请问要如何解决呢，使用的sdk版本是LiteAVSDK_Player_7.1.8771

**Comment by ZhZhZhen** [comment]
默认码率是取得借口的值，如果一开始不设置码率，好像默认播放index为0的码率，所以照着超级播放器那样在视频准备时设置了index码率

**Comment by ZhZhZhen** [comment]
排查到问题，是关闭了硬件加速导致的，我试了一下超级播放器，关闭硬件加速也会有这个情况

**Comment by ZhZhZhen** [comment]
另外这种方式会使TXVodPlayer.setStartTime()失效

**Comment by ZhZhZhen** [comment]
准备事件设置码率
1、会让setStartTime()失效
2、不开硬件加速时，会有小概率闪屏

**Comment by jacky-zhupengpeng** [comment]
有遇到放大视频点击顶部返回到窗口大小 所有activity销毁的情况吗
