### ISSUE TITLE
建议增加解码库

### ISSUE THREAD

**Issue by mSoftDeveloper** [LiteAVSDK/Player_Android#88]
衷心的建议官方大大增加解码库，可以做两个版本，一个是精简版，一个是完整版，这个播放器超好用，唯独就是解码太少，目前的解码只能满足部分的视频需求，各方开发者会集成这个播放器播方更多格式的视频，虽然解码库全了会增加体积，但是有了精简版和完整版就可以让开发者自行选择，同时也辛苦官方大大了，希望官方大大可以支持一下，谢谢啦

**Comment by whalehe** [comment]
您好，所以解码器都支持，确实会增大体积，目前超级播放器基本上支持了所以主流的音视频格式

**Comment by jacky-zhupengpeng** [comment]
hls切片加密的视频  出现TXCVodVideoView: onHLSKeyError这个问题
