### ISSUE TITLE
关于下载功能

### ISSUE THREAD

**Issue by ZhZhZhen** [LiteAVSDK/Player_Android#90]
1、请问有对应的文档吗，监听中hlsKeyVerify()方法作用不明，
2、我像TXVodPlayer.setToken()一样，设置TXVodDownloadDataSource.setToken()，但是不知道是不是因为HLS加密的问题，现在下载一直提示网络连接错误，这种错误提示明显是错的，但是不知道什么原因。
3、对于下载后的hls文件，如何进行加密问题的处理，现在好像只有下载的时候进行了加密验证，如果直接播放本地的hls文件是没有什么加密方式的吗

**Comment by yforyoung** [comment]
同求，请问有什么解决方案吗，HLS加密视频如何下载
